name: cosmetics
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.9.2
dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.3
  lottie: ^3.3.2
dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/fonts/montserrat/
    - assets/fonts/segoeui/

  fonts:
    - family: montserrat
      fonts:
        - asset: assets/fonts/montserrat/montserrat.ttf
          weight: 400

    - family: segoeui
      fonts:
        - asset: assets/fonts/segoeui/segoeui.ttf
          weight: 400
